### ISSUE TITLE
utf8 problem

### ISSUE THREAD

**Issue by tigros** [SanderSade/txt2html#3]
Hi,

Thanks for the project.

You have a pretty serious bug on line [#91](https://github.com/SanderSade/txt2html/blob/ca5796b7f800e2d758991ec9c957d8a2bd800879/txt2html.core/Conversion.cs#L91) of Conversion.cs, that looses the utf8 encoding so chinese japanese etc show as question marks.

All you need i believe is "return _sb.ToString();" instead.

g'day!

**Comment by SanderSade** [comment]
Thank you very much - definitely a bug!

Fixed and will be released as a 2.0.2 shortly.

**Comment by SanderSade** [comment]
- https://github.com/SanderSade/txt2html/releases/tag/2.0.2
- https://www.nuget.org/packages/Sander.txt2html/2.0.2
