### ISSUE TITLE
error on cli

### ISSUE THREAD

**Issue by Owned67** [SanderSade/txt2html#6]
![cmd_mmL4Sj4NzY](https://github.com/SanderSade/txt2html/assets/1497809/85ede00c-da49-4555-a5d9-fd0030f87c7b)
the file was converted and it's good, just annoying popup error...

**Comment by SanderSade** [comment]
Thank you - not sure what was the reason, I'll look into this.

**Comment by SanderSade** [comment]
OK, figured it out. The last version of the txt2html (2.0.2) did not include the console version at all, only the UI. 

So txt2html.exe started was actually the UI and not console - and the UI has a "secret" functionality of converting from console input as well but expecting all of the keys in the cmdline to be input files....

I am going to rename the UI to txt2htmlUI.exe to avoid the confusion, and will include the console as txt2html.exe

**Comment by SanderSade** [comment]
Release 2.0.3 created - https://github.com/SanderSade/txt2html/releases/tag/2.0.3
